let data = [
  {
    "Completed": 1,
    "Suggested": "03/27/2017",
    "Start Date": "03/27/2017",
    "Date Completed": "04/20/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Streamlined CTAs on Cart Page",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "unique selling point",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "04/20/2017",
    "Start Date": "04/20/2017",
    "Date Completed": "05/12/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Desktop - Modify Top Nav to Look Same",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "clicks",
    "Status": "win",
    "Uplift": "113.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "04/20/2017",
    "Start Date": "04/20/2017",
    "Date Completed": "5/5/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Mobile - Brand & Part Type Pages: Start Pgs w Collapsed Fields",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "05/18/2017",
    "Start Date": "05/18/2017",
    "Date Completed": "05/31/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Guest Checkout - Streamlined CTAs on Cart Page",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "06/01/2017",
    "Start Date": "06/01/2017",
    "Date Completed": "07/03/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Landing Page Product Page Only - Coupon Code",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "8%",
    "Proj. Monthly Rev Lift": "$8,646.50",
    "Proj. Monthly Lift in Transactions": 86,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "07/19/2017",
    "Start Date": "07/19/2017",
    "Date Completed": "8/1/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Farmall and Ford Brand Page Personalization",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "13.40%",
    "Proj. Monthly Rev Lift": "$17,707.84",
    "Proj. Monthly Lift in Transactions": 138,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "9/19/2017",
    "Start Date": "9/19/2017",
    "Date Completed": "10/2/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "SLI Landing Page Test",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/30/2017",
    "Start Date": "10/30/2017",
    "Date Completed": "11/21/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Mobile | Pull CTA Just Below Product Grid",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/10/2017",
    "Start Date": "10/10/2017",
    "Date Completed": "10/26/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Guest Checkout - 3rd Iteration - Streamlined CTAs on Cart Page",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "12.90%",
    "Proj. Monthly Rev Lift": "$90,830.08",
    "Proj. Monthly Lift in Transactions": 637,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/30/2017",
    "Start Date": "10/30/2017",
    "Date Completed": "1/9/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "2nd Iteration of Personalization test - Chalmers and Ferguson",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "1/9/2018",
    "Start Date": "1/9/2018",
    "Date Completed": "1/31/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "Brand Grid on HP [M]",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "plp views",
    "Status": "win",
    "Uplift": "54.31%",
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "1/23/2018",
    "Start Date": "1/23/2018",
    "Date Completed": "3/5/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Stacked PDP Tabs [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "add to cart clicks",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "2/12/2018",
    "Start Date": "2/12/2018",
    "Date Completed": "3/13/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Streamlined Mobile Header [M]",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "revenue",
    "Status": "win",
    "Uplift": "4.82%",
    "Proj. Monthly Rev Lift": "$7,159.00",
    "Proj. Monthly Lift in Transactions": 58,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "3/23/2018",
    "Start Date": "3/23/2018",
    "Date Completed": "4/12/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "New Homepage Layout [D]",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "revenue",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "4/26/2018",
    "Start Date": "4/26/2018",
    "Date Completed": "5/14/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Remove Navigation in Checkout [DT]",
    "Device": "DT",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "revenue",
    "Status": "win",
    "Uplift": "3.20%",
    "Proj. Monthly Rev Lift": "$22,521.22",
    "Proj. Monthly Lift in Transactions": 143,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/8/2018",
    "Start Date": "5/8/2018",
    "Date Completed": "5/30/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "HP Catalog Request Banner [M]",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "catalog requests",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/17/2018",
    "Start Date": "5/17/2018",
    "Date Completed": "6/7/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "CTA Language on Cart Page [D]",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "checkout entrances",
    "Status": "win",
    "Uplift": "2.98%",
    "Proj. Monthly Rev Lift": "$21,663.72",
    "Proj. Monthly Lift in Transactions": 153,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "6/7/2018",
    "Start Date": "6/7/2018",
    "Date Completed": "6/29/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "2nd iteration - CTA Language on Cart Page",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "checkout entrances",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "6/25/2018",
    "Start Date": "6/25/2018",
    "Date Completed": "7/12/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Email Capture Banner [M]",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "email subscriptions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "7/13/2018",
    "Start Date": "7/13/2018",
    "Date Completed": "7/30/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "New Visitors Only - Email Capture Banner [M]",
    "Device": "M",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "email subscriptions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "12/27/2018",
    "Start Date": "12/27/2018",
    "Date Completed": "1/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Direct users to cart after ATC [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.98%",
    "Proj. Monthly Rev Lift": "$9,794.00",
    "Proj. Monthly Lift in Transactions": 69,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "1/18/2019",
    "Start Date": "1/18/2019",
    "Date Completed": "2/5/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart: Emphasize \"Checkout Now\" [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "checkout entrances",
    "Status": "win",
    "Uplift": "2.17%",
    "Proj. Monthly Rev Lift": "$13,768.38",
    "Proj. Monthly Lift in Transactions": 96,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "2/5/2019",
    "Start Date": "2/5/2019",
    "Date Completed": "2/28/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - Increase Information Density [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "3/13/2019",
    "Start Date": "3/13/2019",
    "Date Completed": "3/28/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Internet Explorer: Remove Warning Message [D]",
    "Device": "D",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "22.60%",
    "Proj. Monthly Rev Lift": "$11,185.00",
    "Proj. Monthly Lift in Transactions": 82,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "3/13/2019",
    "Start Date": "3/13/2019",
    "Date Completed": "4/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Checkout: Separate Login/Guest [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "5.58%",
    "Proj. Monthly Rev Lift": "$20,634.00",
    "Proj. Monthly Lift in Transactions": 166,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "4/8/2019",
    "Start Date": "4/8/2019",
    "Date Completed": "5/10/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - Desktop Navigation on Tablet [T]",
    "Device": "T",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/1/2019",
    "Start Date": "5/1/2019",
    "Date Completed": "5/10/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "2nd Page Checkout - Restructure [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "6.90%",
    "Proj. Monthly Rev Lift": "$18,046.00",
    "Proj. Monthly Lift in Transactions": 174,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/28/2019",
    "Start Date": "5/28/2019",
    "Date Completed": "6/13/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Brand Pages - Encourage Filtering by Model [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "5.90%",
    "Proj. Monthly Rev Lift": "$14,010.00",
    "Proj. Monthly Lift in Transactions": 107,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "7/3/2019",
    "Start Date": "7/3/2019",
    "Date Completed": "7/18/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - Display Email Signup to New Visitors [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "6.90%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 475,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "7/25/2019",
    "Start Date": "7/25/2019",
    "Date Completed": "8/8/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Brand Page Personalization [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "8.30%",
    "Proj. Monthly Rev Lift": "$19,700.00",
    "Proj. Monthly Lift in Transactions": 156,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "8/5/2019",
    "Start Date": "8/5/2019",
    "Date Completed": "8/21/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "search",
    "Test Name": "Search Results - Encourage Use of Filters [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "9/11/2019",
    "Start Date": "9/11/2019",
    "Date Completed": "9/25/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Brand Pages - Alter CTA to 'View Details' [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/1/2019",
    "Start Date": "10/1/2019",
    "Date Completed": "10/30/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP - Emphasize Brand/Sub-Brand Dropdowns [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "2.34%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "10/30/2019",
    "Start Date": "10/30/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP - Clarify Delivery Badges [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "running",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "11/18/2019",
    "Start Date": "11/18/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - Add PayPal Credit [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "running",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  }
];

const columnOrder = ["Test Name", "Status", "Uplift", "Proj. Monthly Rev Lift", "Proj. Monthly Lift in Transactions", "Page", "Client", "Increase/ Decrease", "Hypothesis", "Device", "Primary Metric", "Suggested", "Start Date", "Date Completed", "Industry", "Priority", "Priority Score", "Report", "Notes", "Completed", "High Traffic", "Highly Visible", "Reduces Friction", "Increases Motivation", "Simple Test Build", "GA", "User Testing", "Heuristic Analysis"];

const formattedData = data.map(test => {
  let formattedTest = {};
  columnOrder.forEach(column => formattedTest[column.toLowerCase()] = test[column]);
  return formattedTest;
});

export default formattedData;