let data = [
  {
    "Completed": 1,
    "Suggested": "01/01/2019",
    "Start Date": "10/26/2018",
    "Date Completed": "11/08/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - Keep Placeholder Text in Search Bar [D]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "prominence of search",
    "Primary Metric": "Search Events",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "11/18/2018",
    "Date Completed": "12/04/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "Homepage: Test Alternate Wording in ‘Add a Vehicle’ Section",
    "Device": "D",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "friction in product options",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "11/20/2018",
    "Date Completed": "12/4/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Separate Transactional and Content Links in Navigation",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "12/07/2018",
    "Date Completed": "01/30/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "category",
    "Test Name": "Brake Pads LP: Alter Primary CTA",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "call to action",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "12/13/2018",
    "Date Completed": "01/11/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "category",
    "Test Name": "Wiper LP Mobile - Remove Certona Module",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "4%",
    "Proj. Monthly Rev Lift": "$6,115.25",
    "Proj. Monthly Lift in Transactions": 135,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "12/21/2018",
    "Date Completed": "1/7/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP - DTM Address Users' Concerns Near Add To Cart",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "unique selling point",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.05%",
    "Proj. Monthly Rev Lift": "$184,792.00",
    "Proj. Monthly Lift in Transactions": "2,411",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/8/2019",
    "Date Completed": "5/22/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - DTM - Skip Interstitial After Add to Cart",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "1/9/2019",
    "Date Completed": "1/23/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP: DTM - Ensure Promo Boxes Don't Look Like Warnings",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "value proposition",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.30%",
    "Proj. Monthly Rev Lift": "$231,057.00",
    "Proj. Monthly Lift in Transactions": "3,038",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "1/22/2019",
    "Date Completed": "2/18/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PLA - Remove Certona on PLA",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "1/23/2019",
    "Date Completed": "2/13/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "other",
    "Test Name": "Store Locator DTM - Add \"Buy Online, Pick Up In-Store",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "value proposition",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.10%",
    "Proj. Monthly Rev Lift": "$75,353.00",
    "Proj. Monthly Lift in Transactions": 939,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "1/23/2019",
    "Date Completed": "1/30/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - Encourage Users to Click Into PDPs",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.21%",
    "Proj. Monthly Rev Lift": "$128,207.70",
    "Proj. Monthly Lift in Transactions": "1,617",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "2/8/2019",
    "Date Completed": "2/27/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PLA - Mobile - Hide Store Banner",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "2/25/2019",
    "Date Completed": "3/13/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "category",
    "Test Name": "Battery LP - DTM - Alter Primary CTA",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "call to action",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "3/11/2019",
    "Date Completed": "3/22/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PLA PDP - Mobile - Add View More Products Button",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "3/29/2019",
    "Date Completed": "4/10/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP - Mobile - Hide Store Banner - All Mobile Traffic",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "4/15/2019",
    "Date Completed": "5/8/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - Mobile - Reduce Vertical Height",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "",
    "Start Date": "4/30/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Checkout - M - Reduce Visual Complexity",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "form usability",
    "Primary Metric": "transactions",
    "Status": "submitted",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "4/30/2019",
    "Date Completed": "5/6/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - DTM - Add Hero Background Image",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "imagery",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "4/30/2019",
    "Date Completed": "5/22/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - M - Make Refine Results Sticky",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "prominence of filters",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "4/30/2019",
    "Date Completed": "5/22/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - D - Clarify Video Thumbnail",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/1/2019",
    "Date Completed": "5/17/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - Mobile - Increase Checkout Button Visibility",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "6/5/2019",
    "Date Completed": "6/21/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - DTM - Hide Free Shipping Threshold Message",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/3/2019",
    "Date Completed": "6/21/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Checkout - DTM - Add Privacy Messaging",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "security messaging",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.40%",
    "Proj. Monthly Rev Lift": "$136,792.00",
    "Proj. Monthly Lift in Transactions": "1,791",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/20/2019",
    "Date Completed": "6/18/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - DTM - Add Product Badges",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "friction in product options",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/21/2019",
    "Date Completed": "6/3/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - DTM - Add Total to Checkout Button",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "0.61%",
    "Proj. Monthly Rev Lift": "$223,800.00",
    "Proj. Monthly Lift in Transactions": "3,044",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "8/12/2019",
    "Date Completed": "8/21/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - DTM - Checkout Button - Secure Checkout Without Total",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "security messaging",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/22/2019",
    "Date Completed": "7/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - DTM - Hide Search Bar",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "prominence of search",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/17/2019",
    "Date Completed": "6/28/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart – DTM – Emphasize Promo Code Field and Button",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "payment information",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "5/23/2019",
    "Date Completed": "6/26/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Checkout - DTM - Hide Promo Code Text Link and Banner",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "payment information",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "6/20/2019",
    "Date Completed": "7/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PLA - M - Emphasize AAV CTA",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "friction in product options",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "6/20/2019",
    "Date Completed": "7/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP/ PDP - DTM - Add In Stock for Ship to Home Items",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "urgency/ scarcity",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "6/20/2019",
    "Date Completed": "8/28/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Batteries PDP - DTM - Emphasize In-Store Installation",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "unique selling point",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "8/21/2019",
    "Date Completed": "8/27/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - DTM - Personalize Page Elements After AAV",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "personalization",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "8/30/2019",
    "Date Completed": "9/20/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - DTM - Add Product Badges II - Alternate Phrases",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "friction in product options",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "7/1/2019",
    "Date Completed": "9/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - DTM - A/A",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "",
    "Start Date": "7/1/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "other",
    "Test Name": "Find Pages - D - Site Navigation",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "transactions",
    "Status": "submitted",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "6/1/2019",
    "Date Completed": "7/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - Duplicate 'Checkout Now' Button at Top of Cart Page II - React",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/15/2019",
    "Date Completed": "10/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "Homepage - DTM - Add Coupons and Deals Page Link",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "value proposition",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/10/2019",
    "Date Completed": "10/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - DTM - Add Chat Style AAV",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "friction in product options",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/4/2019",
    "Date Completed": "10/16/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - D - Prompt Users Who Search for Vehicles to Add a Vehicle",
    "Device": "D",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "prominence of search",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/4/2019",
    "Date Completed": "10/21/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - DTM - Increase Prominence of Fit Confirmation",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "0.51%",
    "Proj. Monthly Rev Lift": "$279,763.00",
    "Proj. Monthly Lift in Transactions": "2,568",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "",
    "Start Date": "10/14/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "other",
    "Test Name": "Advice Page Refresh - Navigation",
    "Device": "DTM",
    "Increase/ Decrease": "",
    "Hypothesis": "",
    "Primary Metric": "none",
    "Status": "running",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/15/2019",
    "Date Completed": "10/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "Home Page Category Test - PLP vs Landing Page",
    "Device": "DTM",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "friction in product options",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/11/2019",
    "Date Completed": "10/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "other",
    "Test Name": "Advice Pages - DTM - List Site Links on Side",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "",
    "Start Date": "10/18/2019",
    "Date Completed": "10/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart Interstitial - DTM - Encourage Users to Checkout Online",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.93%",
    "Proj. Monthly Rev Lift": "$409,902.00",
    "Proj. Monthly Lift in Transactions": "7,835",
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "",
    "Start Date": "10/23/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - Change \"Fast & Free\" to push value-prop more prominently",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "unique selling point",
    "Primary Metric": "transactions",
    "Status": "submitted",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Advance Auto Parts",
    "Industry": "Automotive",
    "Report": "",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "03/27/2017",
    "Start Date": "03/27/2017",
    "Date Completed": "04/20/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Streamlined CTAs on Cart Page",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "04/20/2017",
    "Start Date": "04/20/2017",
    "Date Completed": "05/12/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Desktop - Modify Top Nav to Look Same",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "clicks/ interactions",
    "Primary Metric": "clicks",
    "Status": "win",
    "Uplift": "113.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "04/20/2017",
    "Start Date": "04/20/2017",
    "Date Completed": "5/5/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Mobile - Brand & Part Type Pages: Start Pgs w Collapsed Fields",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "prominence of filters",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "05/18/2017",
    "Start Date": "05/18/2017",
    "Date Completed": "05/31/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Guest Checkout - Streamlined CTAs on Cart Page",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "06/01/2017",
    "Start Date": "06/01/2017",
    "Date Completed": "07/03/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Landing Page Product Page Only - Coupon Code",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "value proposition",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "8%",
    "Proj. Monthly Rev Lift": "$8,646.50",
    "Proj. Monthly Lift in Transactions": 86,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "07/19/2017",
    "Start Date": "07/19/2017",
    "Date Completed": "8/1/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Farmall and Ford Brand Page Personalization",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "imagery",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "13.40%",
    "Proj. Monthly Rev Lift": "$17,707.84",
    "Proj. Monthly Lift in Transactions": 138,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "9/19/2017",
    "Start Date": "9/19/2017",
    "Date Completed": "10/2/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "SLI Landing Page Test",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "personalization",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/10/2017",
    "Start Date": "10/10/2017",
    "Date Completed": "10/26/2017",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Guest Checkout - 3rd Iteration - Streamlined CTAs on Cart Page",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "12.90%",
    "Proj. Monthly Rev Lift": "$90,830.08",
    "Proj. Monthly Lift in Transactions": 637,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/30/2017",
    "Start Date": "10/30/2017",
    "Date Completed": "1/9/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "2nd Iteration of Personalization test - Chalmers and Ferguson",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "imagery",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "1/9/2018",
    "Start Date": "1/9/2018",
    "Date Completed": "1/31/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "Brand Grid on HP [M]",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "plp views",
    "Status": "win",
    "Uplift": "54.31%",
    "Proj. Monthly Rev Lift": 0,
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "1/23/2018",
    "Start Date": "1/23/2018",
    "Date Completed": "3/5/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Stacked PDP Tabs [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "add to cart clicks",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "2/12/2018",
    "Start Date": "2/12/2018",
    "Date Completed": "3/13/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Streamlined Mobile Header [M]",
    "Device": "M",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "revenue",
    "Status": "win",
    "Uplift": "4.82%",
    "Proj. Monthly Rev Lift": "$7,159.00",
    "Proj. Monthly Lift in Transactions": 58,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "3/23/2018",
    "Start Date": "3/23/2018",
    "Date Completed": "4/12/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "New Homepage Layout [D]",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "revenue",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "4/26/2018",
    "Start Date": "4/26/2018",
    "Date Completed": "5/14/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Remove Navigation in Checkout [DT]",
    "Device": "DT",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "revenue",
    "Status": "win",
    "Uplift": "3.20%",
    "Proj. Monthly Rev Lift": "$22,521.22",
    "Proj. Monthly Lift in Transactions": 143,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/8/2018",
    "Start Date": "5/8/2018",
    "Date Completed": "5/30/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "homepage",
    "Test Name": "HP Catalog Request Banner [M]",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product discoverability",
    "Primary Metric": "catalog requests",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/17/2018",
    "Start Date": "5/17/2018",
    "Date Completed": "6/7/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "CTA Language on Cart Page [D]",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "call to action",
    "Primary Metric": "checkout entrances",
    "Status": "win",
    "Uplift": "2.98%",
    "Proj. Monthly Rev Lift": "$21,663.72",
    "Proj. Monthly Lift in Transactions": 153,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "6/7/2018",
    "Start Date": "6/7/2018",
    "Date Completed": "6/29/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "2nd iteration - CTA Language on Cart Page",
    "Device": "D",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "call to action",
    "Primary Metric": "checkout entrances",
    "Status": "inconclusive",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "6/25/2018",
    "Start Date": "6/25/2018",
    "Date Completed": "7/12/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Email Capture Banner [M]",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "clicks/ interactions",
    "Primary Metric": "email subscriptions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "7/13/2018",
    "Start Date": "7/13/2018",
    "Date Completed": "7/30/2018",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "New Visitors Only - Email Capture Banner [M]",
    "Device": "M",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "clicks/ interactions",
    "Primary Metric": "email subscriptions",
    "Status": "loss",
    "Uplift": 0,
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "12/27/2018",
    "Start Date": "12/27/2018",
    "Date Completed": "1/24/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "Direct users to cart after ATC [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "1.98%",
    "Proj. Monthly Rev Lift": "$9,794.00",
    "Proj. Monthly Lift in Transactions": 69,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "1/18/2019",
    "Start Date": "1/18/2019",
    "Date Completed": "2/5/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart: Emphasize \"Checkout Now\" [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "checkout entrances",
    "Status": "win",
    "Uplift": "2.17%",
    "Proj. Monthly Rev Lift": "$13,768.38",
    "Proj. Monthly Lift in Transactions": 96,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "2/5/2019",
    "Start Date": "2/5/2019",
    "Date Completed": "2/28/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "PLP - Increase Information Density [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "3/13/2019",
    "Start Date": "3/13/2019",
    "Date Completed": "3/28/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Internet Explorer: Remove Warning Message [D]",
    "Device": "D",
    "Increase/ Decrease": "Decrease/ Remove",
    "Hypothesis": "distracting content",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "22.60%",
    "Proj. Monthly Rev Lift": "$11,185.00",
    "Proj. Monthly Lift in Transactions": 82,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "3/13/2019",
    "Start Date": "3/13/2019",
    "Date Completed": "4/1/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "Checkout: Separate Login/Guest [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "suggesting a funnel path",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "5.58%",
    "Proj. Monthly Rev Lift": "$20,634.00",
    "Proj. Monthly Lift in Transactions": 166,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "4/8/2019",
    "Start Date": "4/8/2019",
    "Date Completed": "5/10/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - Desktop Navigation on Tablet [T]",
    "Device": "T",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "clicks/ interactions",
    "Primary Metric": "transactions",
    "Status": "inconclusive",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/1/2019",
    "Start Date": "5/1/2019",
    "Date Completed": "5/10/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "checkout",
    "Test Name": "2nd Page Checkout - Restructure [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "form usability",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "6.90%",
    "Proj. Monthly Rev Lift": "$18,046.00",
    "Proj. Monthly Lift in Transactions": 174,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "5/28/2019",
    "Start Date": "5/28/2019",
    "Date Completed": "6/13/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Brand Pages - Encourage Filtering by Model [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "prominence of filters",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "5.90%",
    "Proj. Monthly Rev Lift": "$14,010.00",
    "Proj. Monthly Lift in Transactions": 107,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "7/3/2019",
    "Start Date": "7/3/2019",
    "Date Completed": "7/18/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "global",
    "Test Name": "Global - Display Email Signup to New Visitors [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "clicks/ interactions",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "6.90%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 475,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "7/25/2019",
    "Start Date": "7/25/2019",
    "Date Completed": "8/8/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Brand Page Personalization [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "imagery",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "8.30%",
    "Proj. Monthly Rev Lift": "$19,700.00",
    "Proj. Monthly Lift in Transactions": 156,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "8/5/2019",
    "Start Date": "8/5/2019",
    "Date Completed": "8/21/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "search",
    "Test Name": "Search Results - Encourage Use of Filters [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "prominence of filters",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "9/11/2019",
    "Start Date": "9/11/2019",
    "Date Completed": "9/25/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "plp",
    "Test Name": "Brand Pages - Alter CTA to 'View Details' [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "call to action",
    "Primary Metric": "transactions",
    "Status": "loss",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 1,
    "Suggested": "10/1/2019",
    "Start Date": "10/1/2019",
    "Date Completed": "10/30/2019",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP - Emphasize Brand/Sub-Brand Dropdowns [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "product information",
    "Primary Metric": "transactions",
    "Status": "win",
    "Uplift": "2.34%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "10/30/2019",
    "Start Date": "10/30/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "pdp",
    "Test Name": "PDP - Clarify Delivery Badges [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "payment information",
    "Primary Metric": "transactions",
    "Status": "running",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  },
  {
    "Completed": 0,
    "Suggested": "11/18/2019",
    "Start Date": "11/18/2019",
    "Date Completed": "",
    "Priority": "tba",
    "Priority Score": "tba",
    "Page": "cart",
    "Test Name": "Cart - Add PayPal Credit [DTM]",
    "Device": "DTM",
    "Increase/ Decrease": "Increase/ Add",
    "Hypothesis": "payment information",
    "Primary Metric": "transactions",
    "Status": "running",
    "Uplift": "0.00%",
    "Proj. Monthly Rev Lift": "$0.00",
    "Proj. Monthly Lift in Transactions": 0,
    "Client": "Steiner Tractor",
    "Industry": "Agriculture",
    "Report": "tba",
    "Notes": "",
    "High Traffic": "tba",
    "Highly Visible": "tba",
    "Reduces Friction": "tba",
    "Increases Motivation": "tba",
    "Simple Test Build": "tba",
    "GA": "tba",
    "User Testing": "tba",
    "Heuristic Analysis": "tba"
  }
]

const columnOrder = ["Test Name", "Status", "Uplift", "Proj. Monthly Rev Lift", "Proj. Monthly Lift in Transactions", "Page", "Client", "Increase/ Decrease", "Hypothesis", "Device", "Primary Metric", "Suggested", "Start Date", "Date Completed", "Industry", "Priority", "Priority Score", "Report", "Notes", "Completed", "High Traffic", "Highly Visible", "Reduces Friction", "Increases Motivation", "Simple Test Build", "GA", "User Testing", "Heuristic Analysis"];

const formattedData = data.map(test => {
  let formattedTest = {};
  columnOrder.forEach(column => {
    if (column === "Proj. Monthly Rev Lift"){
      formattedTest["Rev Lift"] = test[column];
      return;
    }
    if (column === "Proj. Monthly Lift in Transactions"){
      formattedTest["Transaction Lift"] = test[column];
      return;
    }
    formattedTest[column.toLowerCase()] = test[column];
  });
  return formattedTest;
});

function sortByColumn(data, columnName, direction) {
  //this is copied from App.js, used to sort data by date completed on initial import
  //TODO: handle sorting by dates, percents, dollar amounts
  columnName = columnName.toLowerCase();
  let sortedData = data.sort(
    function (testA, testB) {
      //if strings, sort alphabetically
      if ((typeof testA[columnName] === "string") && (typeof testB[columnName] === "string")) {
        var textA = testA[columnName].toUpperCase();
        var textB = testB[columnName].toUpperCase();
        if (textA < textB) {
          return -1;
        }
        if (textA > textB) {
          return 1;
        }
        return 0;
      }
      //else sort numerically
      return testA[columnName] - testB[columnName]
    })
  sortedData = direction === "up" ? sortedData : sortedData.reverse();
  return sortedData;
}

export default sortByColumn(formattedData, "Date Completed", "up");